### Health Check
# https://www.krakend.io/docs/service-settings/health/
GET http://localhost:8080/__health HTTP/1.1
Content-Type: application/json


### Mockbin API
GET http://mockbin.com/request?foo=bar&foo=baz&page=1 HTTP/1.1
Content-Type: application/json


### Mockbin API (KrakenD)
GET http://localhost:8080/mockbin?foo=bar&foo=baz&page=1 HTTP/1.1
Content-Type: application/json
