FROM krakend/builder:2.4.3 as builder
RUN apk update
RUN apk add git
RUN mkdir -p /tmp

RUN git clone https://github.com/onliner/krakend-http-cache.git
RUN cd krakend-http-cache && go build -buildmode=plugin -o /tmp/krakend-http-cache.so .

COPY plugins /plugins
RUN cd /plugins/key-auth && go build -buildmode=plugin -o /tmp/krakend-key-auth.so .

FROM devopsfaith/krakend:2.4.3-watch
RUN mkdir -p /etc/krakend-plugins
COPY --from=builder --chown=krakend:nogroup /tmp/krakend-http-cache.so /etc/krakend-plugins
COPY --from=builder --chown=krakend:nogroup /tmp/krakend-key-auth.so /etc/krakend-plugins
