version: '3'

vars:
  BUILD_DIR: '{{.USER_WORKING_DIR}}/build'
  TMP_DIR: '{{.USER_WORKING_DIR}}/tmp'
  BIN_DIR: '{{.USER_WORKING_DIR}}/bin'

env:
  APP_ENV: development

dotenv: ['.env']

tasks:
  download:
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - GOBIN={{.BIN_DIR}} go install github.com/volatiletech/sqlboiler/v4@v4.14.2
      - GOBIN={{.BIN_DIR}} go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-psql@v4.14.2

  install:
    cmds:
      - go mod download
      - go mod tidy

  clean:
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -rf {{.TMP_DIR}}

  db_inspect:
    cmds:
      # using args
      # - atlas schema inspect -u "$DATABASE_URL" > ./db/schema.hcl
      # using atlas.hcl
      - atlas schema inspect -c file://db/atlas-declarative.hcl --env development > ./db/schema.hcl

  # Declarative workflow
  db_apply:
    cmds:
      # using args
      # - atlas schema apply -u "$DATABASE_URL" --to file://db/schema.hcl
      # using atlas.hcl
      - atlas schema apply -c file://db/atlas-declarative.hcl --env development

  # Versioned workflow
  db_create_migration:
    cmds:
      # using args
      # - atlas migrate diff {{.CLI_ARGS}} --dir "file://db/migrations" --to "file://db/schema.hcl" --dev-url "$DATABASE_URL"
      # using atlas.hcl
      - atlas migrate diff {{.CLI_ARGS}} -c file://db/atlas-versioned.hcl --env development

  db_create_seed:
    cmds:
      # using args
      # - atlas migrate new {{.CLI_ARGS}} --dir "file://db/migrations"
      # using atlas.hcl
      - atlas migrate new {{.CLI_ARGS}} -c file://db/atlas-versioned.hcl --env development

  db_migrate:
    cmds:
      # using args
      # - atlas migrate apply --url "$DATABASE_URL" --dir "file://db/migrations"
      # using atlas.hcl
      - atlas migrate apply -c file://db/atlas-versioned.hcl --env development

  db_validate:
    cmds:
      # using args
      # - atlas migrate validate --dir "file://db/migrations" --dev-url "$DATABASE_URL"
      # using atlas.hcl
      - atlas migrate validate -c file://db/atlas-versioned.hcl --env development

  db_lint:
    cmds:
      # using args
      # - atlas migrate lint --git-base "main" --dir "file://db/migrations" --dev-url "$DATABASE_URL"
      # using atlas.hcl
      - atlas migrate lint -c file://db/atlas-versioned.hcl --env development

  sql:
    cmds:
      - bin/sqlboiler bin/sqlboiler-psql

  run:
    cmds:
      - go run cmd/main.go
