// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package schema

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testBlogPosts(t *testing.T) {
	t.Parallel()

	query := BlogPosts()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testBlogPostsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BlogPost{}
	if err = randomize.Struct(seed, o, blogPostDBTypes, true, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BlogPosts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBlogPostsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BlogPost{}
	if err = randomize.Struct(seed, o, blogPostDBTypes, true, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := BlogPosts().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BlogPosts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBlogPostsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BlogPost{}
	if err = randomize.Struct(seed, o, blogPostDBTypes, true, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BlogPostSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := BlogPosts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testBlogPostsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BlogPost{}
	if err = randomize.Struct(seed, o, blogPostDBTypes, true, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := BlogPostExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if BlogPost exists: %s", err)
	}
	if !e {
		t.Errorf("Expected BlogPostExists to return true, but got false.")
	}
}

func testBlogPostsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BlogPost{}
	if err = randomize.Struct(seed, o, blogPostDBTypes, true, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	blogPostFound, err := FindBlogPost(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if blogPostFound == nil {
		t.Error("want a record, got nil")
	}
}

func testBlogPostsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BlogPost{}
	if err = randomize.Struct(seed, o, blogPostDBTypes, true, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = BlogPosts().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testBlogPostsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BlogPost{}
	if err = randomize.Struct(seed, o, blogPostDBTypes, true, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := BlogPosts().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testBlogPostsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	blogPostOne := &BlogPost{}
	blogPostTwo := &BlogPost{}
	if err = randomize.Struct(seed, blogPostOne, blogPostDBTypes, false, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}
	if err = randomize.Struct(seed, blogPostTwo, blogPostDBTypes, false, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = blogPostOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = blogPostTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BlogPosts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testBlogPostsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	blogPostOne := &BlogPost{}
	blogPostTwo := &BlogPost{}
	if err = randomize.Struct(seed, blogPostOne, blogPostDBTypes, false, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}
	if err = randomize.Struct(seed, blogPostTwo, blogPostDBTypes, false, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = blogPostOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = blogPostTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BlogPosts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func blogPostBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *BlogPost) error {
	*o = BlogPost{}
	return nil
}

func blogPostAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *BlogPost) error {
	*o = BlogPost{}
	return nil
}

func blogPostAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *BlogPost) error {
	*o = BlogPost{}
	return nil
}

func blogPostBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *BlogPost) error {
	*o = BlogPost{}
	return nil
}

func blogPostAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *BlogPost) error {
	*o = BlogPost{}
	return nil
}

func blogPostBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *BlogPost) error {
	*o = BlogPost{}
	return nil
}

func blogPostAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *BlogPost) error {
	*o = BlogPost{}
	return nil
}

func blogPostBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *BlogPost) error {
	*o = BlogPost{}
	return nil
}

func blogPostAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *BlogPost) error {
	*o = BlogPost{}
	return nil
}

func testBlogPostsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &BlogPost{}
	o := &BlogPost{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, blogPostDBTypes, false); err != nil {
		t.Errorf("Unable to randomize BlogPost object: %s", err)
	}

	AddBlogPostHook(boil.BeforeInsertHook, blogPostBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	blogPostBeforeInsertHooks = []BlogPostHook{}

	AddBlogPostHook(boil.AfterInsertHook, blogPostAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	blogPostAfterInsertHooks = []BlogPostHook{}

	AddBlogPostHook(boil.AfterSelectHook, blogPostAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	blogPostAfterSelectHooks = []BlogPostHook{}

	AddBlogPostHook(boil.BeforeUpdateHook, blogPostBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	blogPostBeforeUpdateHooks = []BlogPostHook{}

	AddBlogPostHook(boil.AfterUpdateHook, blogPostAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	blogPostAfterUpdateHooks = []BlogPostHook{}

	AddBlogPostHook(boil.BeforeDeleteHook, blogPostBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	blogPostBeforeDeleteHooks = []BlogPostHook{}

	AddBlogPostHook(boil.AfterDeleteHook, blogPostAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	blogPostAfterDeleteHooks = []BlogPostHook{}

	AddBlogPostHook(boil.BeforeUpsertHook, blogPostBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	blogPostBeforeUpsertHooks = []BlogPostHook{}

	AddBlogPostHook(boil.AfterUpsertHook, blogPostAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	blogPostAfterUpsertHooks = []BlogPostHook{}
}

func testBlogPostsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BlogPost{}
	if err = randomize.Struct(seed, o, blogPostDBTypes, true, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BlogPosts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBlogPostsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BlogPost{}
	if err = randomize.Struct(seed, o, blogPostDBTypes, true); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(blogPostColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := BlogPosts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testBlogPostToOneUserUsingAuthor(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local BlogPost
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, blogPostDBTypes, true, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.AuthorID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Author().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := BlogPostSlice{&local}
	if err = local.L.LoadAuthor(ctx, tx, false, (*[]*BlogPost)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Author == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Author = nil
	if err = local.L.LoadAuthor(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Author == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testBlogPostToOneSetOpUserUsingAuthor(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a BlogPost
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, blogPostDBTypes, false, strmangle.SetComplement(blogPostPrimaryKeyColumns, blogPostColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetAuthor(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Author != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.AuthorBlogPosts[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.AuthorID, x.ID) {
			t.Error("foreign key was wrong value", a.AuthorID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.AuthorID))
		reflect.Indirect(reflect.ValueOf(&a.AuthorID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.AuthorID, x.ID) {
			t.Error("foreign key was wrong value", a.AuthorID, x.ID)
		}
	}
}

func testBlogPostToOneRemoveOpUserUsingAuthor(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a BlogPost
	var b User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, blogPostDBTypes, false, strmangle.SetComplement(blogPostPrimaryKeyColumns, blogPostColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetAuthor(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveAuthor(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Author().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Author != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.AuthorID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.AuthorBlogPosts) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testBlogPostsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BlogPost{}
	if err = randomize.Struct(seed, o, blogPostDBTypes, true, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBlogPostsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BlogPost{}
	if err = randomize.Struct(seed, o, blogPostDBTypes, true, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := BlogPostSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testBlogPostsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &BlogPost{}
	if err = randomize.Struct(seed, o, blogPostDBTypes, true, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := BlogPosts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	blogPostDBTypes = map[string]string{`ID`: `bigint`, `Title`: `character varying`, `Body`: `text`, `AuthorID`: `bigint`}
	_               = bytes.MinRead
)

func testBlogPostsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(blogPostPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(blogPostAllColumns) == len(blogPostPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BlogPost{}
	if err = randomize.Struct(seed, o, blogPostDBTypes, true, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BlogPosts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, blogPostDBTypes, true, blogPostPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testBlogPostsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(blogPostAllColumns) == len(blogPostPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &BlogPost{}
	if err = randomize.Struct(seed, o, blogPostDBTypes, true, blogPostColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := BlogPosts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, blogPostDBTypes, true, blogPostPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(blogPostAllColumns, blogPostPrimaryKeyColumns) {
		fields = blogPostAllColumns
	} else {
		fields = strmangle.SetComplement(
			blogPostAllColumns,
			blogPostPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := BlogPostSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testBlogPostsUpsert(t *testing.T) {
	t.Parallel()

	if len(blogPostAllColumns) == len(blogPostPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := BlogPost{}
	if err = randomize.Struct(seed, &o, blogPostDBTypes, true); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BlogPost: %s", err)
	}

	count, err := BlogPosts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, blogPostDBTypes, false, blogPostPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize BlogPost struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert BlogPost: %s", err)
	}

	count, err = BlogPosts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
