### Hello world
GET https://localhost HTTP/1.1


### Mockbin API
GET https://mockbin.com/request?foo=bar&foo=baz&page=1 HTTP/1.1
Content-Type: application/json


### Mockbin Proxy 1
GET https://localhost/mockbin01/request?foo=bar&foo=baz&page=1 HTTP/1.1
Content-Type: application/json
